#version 450
#extension GL_ARB_compute_shader : enable
#extension GL_ARB_shader_storage_buffer_object : enable

struct BoidData {
    vec2 pos;
    vec2 vel;
};

layout( std430, binding=5 ) buffer BoidBuffer
{
    BoidData boids[];
};

uniform uint gridSize;

layout( local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

void main() {

    uint gid = gl_GlobalInvocationID.x;
    if (gid >= boids.length()) return;
}